### ISSUE TITLE
Add the ability to track multiple players at once

### ISSUE THREAD

**Issue by Libreh** [mt1006/mc-mocap-mod#10]
Either by allowing multiple `/mocap recording start`s or by adding a trackOtherPlayers setting, idk something like this would be nice
Adding fire charge portal lighting would also be very much appreciated, no pressure though

**Comment by mt1006** [comment]
I have plans to add ability to start multiple recordings in the next version (1.4). Also as I mentioned previously I plan to add tracking all the block changes, so it should fix the issue with the fire charge and other block actions that are not recorded. For now you can try Forge version, as it handles block actions a bit differently and it should work on it.
As for when 1.4 will be released, idk. I won't have much time in the next few months and also I have other projects that I'm working on, so it's very likely it will be even next year.

**Comment by mt1006** [comment]
It took a while, but it's now in alpha: https://github.com/mt1006/mc-mocap-mod/releases/tag/Mocap-1.4-alpha-1
