### ISSUE TITLE
Bug to start scene

### ISSUE THREAD

**Issue by seriousfreezing** [mt1006/mc-mocap-mod#12]
![image](https://github.com/mt1006/mc-mocap-mod/assets/66693072/15e5e43f-be59-439d-91e1-f85e6dc5c318)

**Comment by mt1006** [comment]
Could you send me a minecraft version, a mod loader and a list of mods you were using? If error doesn't appear for every recording and you don't know how to reproduce it with new recording, please send also world (or recording from ```[world directory]/mocap_files/recordings``` if you don't want to send the entire world) and if possible, stack trace from logs which should appear at the same time as the error message on a chat?
I know it's a lot, but I won't find a bug without it.

**Comment by seriousfreezing** [comment]
Forge 43.3.0 - Minecraft 1.19.2
[mocap_files.zip](https://github.com/mt1006/mc-mocap-mod/files/12755284/mocap_files.zip)
![image](https://github.com/mt1006/mc-mocap-mod/assets/66693072/a5508a1b-1dcf-47f0-af19-a8451bc1b652)
If you don't want to download them one by one, download my "Expansive Expedition" modpack, which is very close to the version I have

**Comment by mt1006** [comment]
Thanks, I will look into this issue

**Comment by mt1006** [comment]
I've found the issue. It was caused by incompatibility with JourneyMap. I'll release a fix most likely tomorrow.
