### ISSUE TITLE
Recording with Different Mobs

### ISSUE THREAD

**Issue by Anku1990** [mt1006/mc-mocap-mod#19]
Hi developer, I want to record my player with the mocap but as a different mob or entity like cow, parrot, sheep, wolf etc.  how can i do this Or is this function available in Mocap ?

**Comment by mt1006** [comment]
It is available. First you need to add recording to a scene. Then edit it using ```/mocap scenes modify <scene_name> <element_position> playerAsEntity enabled <entity_id>```

**Comment by Anku1990** [comment]
What is element position ?

**Comment by Anku1990** [comment]
Wow... I figure it out. thankyou so much. 🙏
