### ISSUE TITLE
Second layer

### ISSUE THREAD

**Issue by KlashRaick** [mt1006/mc-mocap-mod#2]
Hello, when starting recording on the character, the second layer is not displayed

**Comment by mt1006** [comment]
You mean second skin layer on fake player? Also, which version do you use?

**Comment by KlashRaick** [comment]
Yes, 1.19.2

**Comment by mt1006** [comment]
For me it properly shows second layer, how exactly did you cause it?

**Comment by mt1006** [comment]
Also, it doesn't show only for a moment or for the entire playback?

**Comment by KlashRaick** [comment]
I threw out some mods from the assembly that somehow influenced the players and as a result the case turned out to be https://modrinth.com/mod/vmp-fabric

**Comment by mt1006** [comment]
Ok, I'm closing issue for now. Later, I might try to fix this compatibility issue, but we'll see.
