### ISSUE TITLE
Replace Player with Villager or Mob

### ISSUE THREAD

**Issue by EggHeadzz** [mt1006/mc-mocap-mod#22]
Hi, first I have to say Mocap is awesome ! I love how you can play the record over and over. 
Now I'm wondering is it possible to replace the player with something else like villager ? Or you can only the skin at the moment ?

Thanks

**Comment by mt1006** [comment]
It's possible, see https://github.com/mt1006/mc-mocap-mod/issues/19#issuecomment-1889358275. As for the `element_position` in this command, you can get them using `/mocap scenes listElements`, but if you have only one element in the scene it should be `1`.
