### ISSUE TITLE
FSit Incompatibility

### ISSUE THREAD

**Issue by MrZeroSkill** [mt1006/mc-mocap-mod#28]
Tbh I thought the mods would be compatible, given that sitting and crawling are just repurposed existing animations for riding and swimming.

When playing back recordings if I had used FSit at all, the playback would not show the player sitting down or crawling. Unsure if this would be the same type of fix as #14. I'm using Mocap 1.3.4 and FSit 2.3.4 for Minecraft 1.20.4.

**Comment by mt1006** [comment]
Crawling seems to work fine. As for sitting, you need to enable `trackOtherEntities` setting first (use `/mocap settings trackOtherEntities true`).
