### ISSUE TITLE
i'll pay you 100 bucks if you get this fixed ASAP

### ISSUE THREAD

**Issue by i-drove-over-a-man-in-2008** [mt1006/mc-mocap-mod#35]
hello again! 
my name is ivorycello, i use your mod for my minecraft cinematic series on youtube called "whitepine"
i depend on this mod to get new episodes out, however there's a bug that is so bad it cost me a week's worth of work.

when there's a lot of recordings playing at once, they all start playing slower incrementally. and i mean SLOW. i needed a shot with 40 people walking around at once and all their movement halted to a crawl. its like they're all stuck in slow motion.

its hard to explain over text, if you link me your discord, we can talk there easier.
i'll literally paypal you 100 bucks if you get this fixed asap, i need this to work.

**Comment by mt1006** [comment]
Hi, first of all, in the future I may add some link to donations, but for now I would feel bad taking money from you for fixing stuff, so I will try to fix it, but I won't take any money.

As for the issue itself, I tried a few hundreds players and it works fine, but I used single recording and player profile, so this might be the reason. You can invite me on discord, it's just mt1006

**Comment by i-drove-over-a-man-in-2008** [comment]
okay, i sent a request on discord. you're very generous, thank you so much T-T i hope you open donations soon, i feel very bad dragging you through the mud of my production problems. also yes i was using around 40 instances, each with a different skin [via mineskin] and i also gave everyone slowness 1, because the default walking speed in minecraft was too fast for the shot. however they slowed down to 0.5x speed and less, their jumping even was in slow motion. i'm also using a few other mods but i tried disabling them to no avail. if its just a problem on my end that would be amazing, so i'll try to do the thing you did with 100 recordings with a single player profile. 

tysmmm qwq

**Comment by i-drove-over-a-man-in-2008** [comment]
weird server lag on my one world, probably not a fault of the mod
