### ISSUE TITLE
Save fails most times

### ISSUE THREAD

**Issue by hablethedev** [mt1006/mc-mocap-mod#37]
Hi, I'm trying to test Mocap, Flashback, and Skin Shuffle (Sodium and Lithium too of course) together.

Every time I run /mocap recording stop then /mocap recording save [name] it fails.

I have no idea why and this worked once before, on a different profile.

Here's the chat (I just walked in a straight line)

![image](https://github.com/user-attachments/assets/6a68b8be-4e9c-4159-8340-a99559bdceac)

Ask for any more info, I'd assume this is user error.

Edit: Fabric 1.21.1

**Comment by mt1006** [comment]
Does leaving and rejoining world help?

**Comment by hablethedev** [comment]
> Does leaving and rejoining world help?

Seems not, no 3:
(Sorry for slow reply)

**Comment by mt1006** [comment]
I was able to reproduce similar issue using Flashback, but in that case, rejoining world solved issue. I'm going to release 1.4-alpha-1 in a few days, which will include patch for it. Then you'll be able to check if it helped with your issue. I'll let you know about the release.

**Comment by mt1006** [comment]
https://github.com/mt1006/mc-mocap-mod/releases/tag/Mocap-1.4-alpha-1
Check if issue is still present on this version.

**Comment by hablethedev** [comment]
![image](https://github.com/user-attachments/assets/af83f990-086b-40b8-882e-4a12e2aaf1b5)
It seems to work!! Thanks!
