### ISSUE TITLE
to_remove value not functioning as intended? (1.21)

### ISSUE THREAD

**Issue by Friskini** [mt1006/mc-mocap-mod#39]
When using /mocap scenes remove_from <scene_name> the following asks for what I can only assume to be the recording name (<to_remove>) you want to remove from the scene, but when I try to put the name of the recording, it responds as if I put in an incorrect value. 

Is it possible I'm misunderstanding the function of the command?

![Screenshot 2024-10-19 201102](https://github.com/user-attachments/assets/2efeea3b-9108-4c88-b806-57c16d8c69d7)
![Screenshot 2024-10-19 202326](https://github.com/user-attachments/assets/f46df652-e96f-422a-b881-a5efb54f3395)

**Comment by mt1006** [comment]
You need to give it a position of the scene element - currently 1, 2 and so on, in the 1.4 I'll probably add suggestions for this argument and some kind of suffix to make identifying elements easier. You can list scene elements and their positions using `/mocap scenes list <scene_name>`.

**Comment by Friskini** [comment]
Oh awesome okay thank you! Never would've guessed that lmao. I appreciate it!
