### ISSUE TITLE
[Incompatibility] Hat/Second layer won't display.

### ISSUE THREAD

**Issue by JLUsr** [mt1006/mc-mocap-mod#4]
This is different than #2. This is an issue between the mod [Soul fire'd](https://www.curseforge.com/minecraft/mc-mods/soul-fired) v3.0.0.0 and v1.2 of MoCap for Fabric 1.19.2

When Soul fire'd is installed the Motion Caption of the player won't have the hat/second layer of their skin enabled.

**Comment by mt1006** [comment]
Ok, I'll try to fix that too. Thanks for reporting.
