### ISSUE TITLE
Adding skins to playback command not working? (1.21)

### ISSUE THREAD

**Issue by Friskini** [mt1006/mc-mocap-mod#40]
Somewhat similar issue to my other post. When adding a name and mineskin URL to a recording that I'm adding to a scene, it gets stuck at the <start_delay> value and doesn't recognize anything I put in. I tried copy pasting the exact command I used in the 1.20.4 version but it didn't work either.

![Screenshot 2024-10-19 202858](https://github.com/user-attachments/assets/36549270-4570-4094-836c-a5dbe8e08c6b)
![Screenshot 2024-10-19 203030](https://github.com/user-attachments/assets/b3b0dc6b-5c1f-4850-8560-837ab0977f82)

**Comment by mt1006** [comment]
That's actually a bug, and I'll fix it most likely in the next alpha

**Comment by mt1006** [comment]
Also note that there's a 1.3.8 version for 1.21
