### ISSUE TITLE
[Feature Request] Playback as mob

### ISSUE THREAD

**Issue by blockerlocker** [mt1006/mc-mocap-mod#42]
I thought it'd be neat to be able to play back MoCap recordings as a mob or entity instead of as a player, that way you can make complicated scenes with mob as well. For the most part it would just be using the position and rotation of the mob, as well as mainhand, offhand, and armor contents I imagine.

**Comment by mt1006** [comment]
It's possible, https://github.com/mt1006/mc-mocap-mod/issues/19#issuecomment-1889358275
