### ISSUE TITLE
Cannot play sitting pose

### ISSUE THREAD

**Issue by Snownee** [mt1006/mc-mocap-mod#5]
Hello, I am trying to record a movement of a player riding boat in Fabric 1.19.2, v1.2.1. Although it does not render the player's vehicle, it would be ideal if it could play the sitting pose correctly

**Comment by mt1006** [comment]
I checked it and sitting pose is directly determined by whether the player is riding other entity. I have plans to add the ability to record vehicles in the future so it will be fixed then as well. As for when it would be, most likely in April (in the worst case May).

**Comment by pupe** [comment]
I'm not sure of course, but now it seems to be June

**Comment by mt1006** [comment]
Yes, sorry that it tooks so long but I'm still working on a new version. I was working on update to my other mod and generally I haven't got much time and now I don't have much motivation, so work goes rather slowly. I'll try to finish it by the end of June, but I'll not promise anything.
